Listen = "0.0.0.0:5678"
ProxyURL = ""
MysqlDns = "root:mhSCk0NheGhmtsha@tcp(geekai-mysql:3306)/geekai_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "/static"
TikaHost = "http://geekai-tika:9998"

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80"
  MaxAge = 86400

[AdminSession]
  SecretKey = "wr1uzwz2meai4z9j0e0tsyf6x523ui6zpnyaim4x2x37meakv13349llqpipyk40"
  MaxAge = 8640000

[Redis]
  Host = "geekai-redis"
  Port = 6379
  Password = "mhSCk0NheGhmtsha"
  DB = 0

[ApiConfig]
  ApiURL = "https://sapi.geekai.me"
  AppId = ""
  Token = ""

[SMS]
  Active = "Ali"
  [SMS.Ali]
    AccessKey = ""
    AccessSecret = ""
    Product = "Dysmsapi"
    Domain = "dysmsapi.aliyuncs.com"
    Sign = ""
    CodeTempId = ""
  [SMS.Bao]
    Username = ""
    Password = ""
    Domain = "api.smsbao.com"
    Sign = "【极客学长】"
    CodeTemplate = "您的验证码是{code}。5分钟有效，若非本人操作，请忽略本短信。"

[OSS]
  Active = "Local"
  [OSS.Local]
    BasePath = "./static/upload"
    BaseURL = "/static/upload"
  [OSS.Minio]
    Endpoint = ""
    AccessKey = ""
    AccessSecret = ""
    Bucket = "geekai"
    SubDir = ""
    UseSSL = false
    Domain = ""
  [OSS.QiNiu]
    Zone = "z2"
    AccessKey = ""
    AccessSecret = ""
    Bucket = ""
    SubDir = ""
    Domain = ""
  [OSS.AliYun]
    Endpoint = "oss-cn-hangzhou.aliyuncs.com"
    AccessKey = ""
    AccessSecret = ""
    Bucket = "geekai"
    SubDir = ""
    Domain = ""

# 支付宝商户支付
[AlipayConfig]
  Enabled = false # 启用支付宝支付通道
  SandBox = false # 是否启用沙盒模式
  UserId = "2088721020750581" # 商户ID
  AppId = "9021000131658023" # App Id
  PrivateKey = "certs/alipay/privateKey.txt" # 应用私钥
  PublicKey = "certs/alipay/appPublicCert.crt" # 应用公钥证书
  AlipayPublicKey = "certs/alipay/alipayPublicCert.crt" # 支付宝公钥证书
  RootCert = "certs/alipay/alipayRootCert.crt" # 支付宝根证书

# 虎皮椒支付
[HuPiPayConfig]
  Enabled = false
  AppId = ""
  AppSecret = ""
  ApiURL = "https://api.xunhupay.com"

# 微信商户支付
[WechatPayConfig]
  Enabled = false
  AppId = "" # 商户应用ID
  MchId = "" # 商户号
  SerialNo = "" # API 证书序列号
  PrivateKey = "certs/alipay/privateKey.txt" # API 证书私钥文件路径，跟支付宝一样，把私钥文件拷贝到对应的路径，证书路径要映射到容器内
  ApiV3Key = "" # APIV3 私钥，这个是你自己在微信支付平台设置的

# 易支付
[GeekPayConfig]
  Enabled = true
  AppId = "" # 商户ID
  PrivateKey = "" # 商户私钥
  ApiURL = "https://pay.geekai.cn"
  Methods = ["alipay", "wxpay", "qqpay", "jdpay", "douyin", "paypal"] # 支持的支付方式